@startuml


object User
object Bottom
object Top
object Orderline
object Order
object Cupcake


User --o Order
Order --* Orderline
Orderline --* Cupcake
Cupcake --* Top
Cupcake --* Bottom











@enduml
