@startuml

object Admin
object User
object Bottom
object Top
object Orderline
object Order


User --o Admin
Admin --o Order
User --o Order
Order --* Orderline
Orderline --* Top
Orderline --* Bottom











@enduml
